  let fuels = [
    { key: '0', text: '0: No Fuel'},
    { key: '0', text: '0: No Fuel'},
    { key: 'none', text: 'none: No Fuel'},
    { key: 'rock', text: 'rock: No Fuel'},
    { key: 'water', text: 'water: No Fuel'},
    { key: '1', text: '1: Short grass'},
    { key: '1', text: '1: Short grass'},
    { key: '2', text: '2: Timber grass and understory'},
    { key: '2', text: '2: Timber grass and understory'},
    { key: '3', text: '3: Tall grass'},
    { key: '3', text: '3: Tall grass'},
    { key: '4', text: '4: Chaparral'},
    { key: '4', text: '4: Chaparral'},
    { key: '5', text: '5: Brush'},
    { key: '5', text: '5: Brush'},
    { key: '6', text: '6: Dormant brush, hardwood slash'},
    { key: '6', text: '6: Dormant brush, hardwood slash'},
    { key: '7', text: '7: Southern rough'},
    { key: '7', text: '7: Southern rough'},
    { key: '8', text: '8: Short needle litter'},
    { key: '8', text: '8: Short needle litter'},
    { key: '9', text: '9: Long needle or hardwood litter'},
    { key: '9', text: '9: Long needle or hardwood litter'},
    { key: '10', text: '10: Timber litter & understory'},
    { key: '10', text: '10: Timber litter & understory'},
    { key: '11', text: '11: Light logging slash'},
    { key: '11', text: '11: Light logging slash'},
    { key: '12', text: '12: Medium logging slash'},
    { key: '12', text: '12: Medium logging slash'},
    { key: '13', text: '13: Heavy logging slash'},
    { key: '13', text: '13: Heavy logging slash'},
    { key: '101', text: '101: Short, sparse, dry climate grass'},
    { key: '101', text: '101: Short, sparse, dry climate grass'},
    { key: 'gr1', text: 'gr1: Short, sparse, dry climate grass'},
    { key: '102', text: '102: Low load, dry climate grass'},
    { key: '102', text: '102: Low load, dry climate grass'},
    { key: 'gr2', text: 'gr2: Low load, dry climate grass'},
    { key: '103', text: '103: Low load, very coarse, humid climate grass'},
    { key: '103', text: '103: Low load, very coarse, humid climate grass'},
    { key: 'gr3', text: 'gr3: Low load, very coarse, humid climate grass'},
    { key: '104', text: '104: Moderate load, dry climate grass'},
    { key: '104', text: '104: Moderate load, dry climate grass'},
    { key: 'gr4', text: 'gr4: Moderate load, dry climate grass'},
    { key: '105', text: '105: Low load, humid climate grass'},
    { key: '105', text: '105: Low load, humid climate grass'},
    { key: 'gr5', text: 'gr5: Low load, humid climate grass'},
    { key: '106', text: '106: Moderate load, humid climate grass'},
    { key: '106', text: '106: Moderate load, humid climate grass'},
    { key: 'gr6', text: 'gr6: Moderate load, humid climate grass'},
    { key: '107', text: '107: High load, dry climate grass'},
    { key: '107', text: '107: High load, dry climate grass'},
    { key: 'gr7', text: 'gr7: High load, dry climate grass'},
    { key: '108', text: '108: High load, very coarse, humid climate grass'},
    { key: '108', text: '108: High load, very coarse, humid climate grass'},
    { key: 'gr8', text: 'gr8: High load, very coarse, humid climate grass'},
    { key: '109', text: '109: Very high load, humid climate grass'},
    { key: '109', text: '109: Very high load, humid climate grass'},
    { key: 'gr9', text: 'gr9: Very high load, humid climate grass'},
    { key: '121', text: '121: Low load, dry climate grass-shrub'},
    { key: '121', text: '121: Low load, dry climate grass-shrub'},
    { key: 'gs1', text: 'gs1: Low load, dry climate grass-shrub'},
    { key: '122', text: '122: Moderate load, dry climate grass-shrub'},
    { key: '122', text: '122: Moderate load, dry climate grass-shrub'},
    { key: 'gs2', text: 'gs2: Moderate load, dry climate grass-shrub'},
    { key: '123', text: '123: Moderate load, humid climate grass-shrub'},
    { key: '123', text: '123: Moderate load, humid climate grass-shrub'},
    { key: 'gs3', text: 'gs3: Moderate load, humid climate grass-shrub'},
    { key: '124', text: '124: High load, humid climate grass-shrub'},
    { key: '124', text: '124: High load, humid climate grass-shrub'},
    { key: 'gs4', text: 'gs4: High load, humid climate grass-shrub'},
    { key: '141', text: '141: Low load, dry climate shrub'},
    { key: '141', text: '141: Low load, dry climate shrub'},
    { key: 'sh1', text: 'sh1: Low load, dry climate shrub'},
    { key: '142', text: '142: Moderate load, dry climate shrub'},
    { key: '142', text: '142: Moderate load, dry climate shrub'},
    { key: 'sh2', text: 'sh2: Moderate load, dry climate shrub'},
    { key: '143', text: '143: Moderate load, humid climate shrub'},
    { key: '143', text: '143: Moderate load, humid climate shrub'},
    { key: 'sh3', text: 'sh3: Moderate load, humid climate shrub'},
    { key: '144', text: '144: Low load, humid climate timber-shrub'},
    { key: '144', text: '144: Low load, humid climate timber-shrub'},
    { key: 'sh4', text: 'sh4: Low load, humid climate timber-shrub'},
    { key: '145', text: '145: High load, dry climate shrub'},
    { key: '145', text: '145: High load, dry climate shrub'},
    { key: 'sh5', text: 'sh5: High load, dry climate shrub'},
    { key: '146', text: '146: Low load, humid climate shrub'},
    { key: '146', text: '146: Low load, humid climate shrub'},
    { key: 'sh6', text: 'sh6: Low load, humid climate shrub'},
    { key: '147', text: '147: Very high load, dry climate shrub'},
    { key: '147', text: '147: Very high load, dry climate shrub'},
    { key: 'sh7', text: 'sh7: Very high load, dry climate shrub'},
    { key: '148', text: '148: High load, humid climate shrub'},
    { key: '148', text: '148: High load, humid climate shrub'},
    { key: 'sh8', text: 'sh8: High load, humid climate shrub'},
    { key: '149', text: '149: Very high load, humid climate shrub'},
    { key: '149', text: '149: Very high load, humid climate shrub'},
    { key: 'sh9', text: 'sh9: Very high load, humid climate shrub'},
    { key: '161', text: '161: Light load, dry climate timber-grass-shrub'},
    { key: '161', text: '161: Light load, dry climate timber-grass-shrub'},
    { key: 'tu1', text: 'tu1: Light load, dry climate timber-grass-shrub'},
    { key: '162', text: '162: Moderate load, humid climate timber-shrub'},
    { key: '162', text: '162: Moderate load, humid climate timber-shrub'},
    { key: 'tu2', text: 'tu2: Moderate load, humid climate timber-shrub'},
    { key: '163', text: '163: Moderate load, humid climate timber-grass-shrub'},
    { key: '163', text: '163: Moderate load, humid climate timber-grass-shrub'},
    { key: 'tu3', text: 'tu3: Moderate load, humid climate timber-grass-shrub'},
    { key: '164', text: '164: Dwarf conifer understory'},
    { key: '164', text: '164: Dwarf conifer understory'},
    { key: 'tu4', text: 'tu4: Dwarf conifer understory'},
    { key: '165', text: '165: Very high load, dry climate timber-shrub'},
    { key: '165', text: '165: Very high load, dry climate timber-shrub'},
    { key: 'tu5', text: 'tu5: Very high load, dry climate timber-shrub'},
    { key: '181', text: '181: Low load, compact conifer litter'},
    { key: '181', text: '181: Low load, compact conifer litter'},
    { key: 'tl1', text: 'tl1: Low load, compact conifer litter'},
    { key: '182', text: '182: Low load broadleaf litter'},
    { key: '182', text: '182: Low load broadleaf litter'},
    { key: 'tl2', text: 'tl2: Low load broadleaf litter'},
    { key: '183', text: '183: Moderate load conifer litter'},
    { key: '183', text: '183: Moderate load conifer litter'},
    { key: 'tl3', text: 'tl3: Moderate load conifer litter'},
    { key: '184', text: '184: Small downed logs'},
    { key: '184', text: '184: Small downed logs'},
    { key: 'tl4', text: 'tl4: Small downed logs'},
    { key: '185', text: '185: High load conifer litter'},
    { key: '185', text: '185: High load conifer litter'},
    { key: 'tl5', text: 'tl5: High load conifer litter'},
    { key: '186', text: '186: High load broadleaf litter'},
    { key: '186', text: '186: High load broadleaf litter'},
    { key: 'tl6', text: 'tl6: High load broadleaf litter'},
    { key: '187', text: '187: Large downed logs'},
    { key: '187', text: '187: Large downed logs'},
    { key: 'tl7', text: 'tl7: Large downed logs'},
    { key: '188', text: '188: Long-needle litter'},
    { key: '188', text: '188: Long-needle litter'},
    { key: 'tl8', text: 'tl8: Long-needle litter'},
    { key: '189', text: '189: Very high load broadleaf litter'},
    { key: '189', text: '189: Very high load broadleaf litter'},
    { key: 'tl9', text: 'tl9: Very high load broadleaf litter'},
    { key: '201', text: '201: Low load activity fuel'},
    { key: '201', text: '201: Low load activity fuel'},
    { key: 'sb1', text: 'sb1: Low load activity fuel'},
    { key: '202', text: '202: Moderate load activity or low load blowdown'},
    { key: '202', text: '202: Moderate load activity or low load blowdown'},
    { key: 'sb2', text: 'sb2: Moderate load activity or low load blowdown'},
    { key: '203', text: '203: High load activity fuel or moderate load blowdown'},
    { key: '203', text: '203: High load activity fuel or moderate load blowdown'},
    { key: 'sb3', text: 'sb3: High load activity fuel or moderate load blowdown'},
    { key: '204', text: '204: High load blowdown'},
    { key: '204', text: '204: High load blowdown'},
    { key: 'sb4', text: 'sb4: High load blowdown'},
    { key: '301', text: '301: chaparral, type=chamise, depth=6, deadFraction=0.5'},
    { key: '301', text: '301: chaparral, type=chamise, depth=6, deadFraction=0.5'},
    { key: 'chaparral/type=chamise/depth=6/deadFraction=0.5', text: 'chaparral/type=chamise/depth=6/deadFraction=0.5: chaparral, type=chamise, depth=6, deadFraction=0.5'},
    { key: '401', text: '401: pg, age=20, basal=120, cover=.8, height=5'},
    { key: '401', text: '401: pg, age=20, basal=120, cover=.8, height=5'},
    { key: 'pg/age=20/basal=120/cover=.8/height=5', text: 'pg/age=20/basal=120/cover=.8/height=5: pg, age=20, basal=120, cover=.8, height=5'},
    { key: '501', text: '501: Aspen-shrub 50%'},
    { key: '501', text: '501: Aspen-shrub 50%'},
    { key: 'aspenShrub50', text: 'aspenShrub50: Aspen-shrub 50%'},
  ]
